### ISSUE TITLE
46. Update ADMT website: improve instructions on how to open NVS issues on the AVTT GitHub

### ISSUE THREAD

**Issue by vpaba** [nvs-vocabs/ArgoVocabs_Meetings#11]
Instructions are outdated in: http://www.argodatamgt.org/Documentation/Argo-vocabulary-server

**Comment by vpaba** [comment]
Sent @tcarval updated text to review and publish

**Comment by gmaze** [comment]
May also be nice to add on the ADMT website a few line about the argopy utility to fetch the NVS and retrieve Argo reference tables easily in python: 
- doc: https://argopy.readthedocs.io/en/latest/metadata_fetching.html#reference-tables
- api: https://argopy.readthedocs.io/en/latest/generated/argopy.utilities.ArgoNVSReferenceTables.html
