### ISSUE TITLE
20. Update ADMT website: add DAC resource webpage with links to AVTT GitHub dashboard

### ISSUE THREAD

**Issue by vpaba** [nvs-vocabs/ArgoVocabs_Meetings#5]

**Comment by cgourcuf** [comment]
This was done: http://www.argodatamgt.org/Documentation/Argo-vocabulary-server
(Note that the information provided will be improved in a new version of the ADMT website, in preparation)

**Comment by gmaze** [comment]
Would be nice to also have a link or an example of the **argopy. ArgoNVSReferenceTables** feature that easily provides access and search to reference tables from python:
https://argopy.readthedocs.io/en/latest/metadata_fetching.html#reference-tables
https://argopy.readthedocs.io/en/latest/generated/argopy.related.ArgoNVSReferenceTables.html

**Comment by cgourcuf** [comment]
Ok, thanks @gmaze for the suggestion. I will consider that for the new version of the Argo Vocabulary webpage on argodatamgt.org :-)
